# Generated by Django 5.2.3 on 2025-06-28 15:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('STD', 'Standard'), ('DLX', 'Deluxe'), ('STE', 'Suite')], max_length=3)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('estado', models.CharField(choices=[('RES', 'Reservada'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], default='RES', max_length=3)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(choices=[('EFC', 'Efectivo'), ('TDC', 'Tarjeta crédito'), ('TDB', 'Tarjeta débito'), ('PAY', 'PayPal')], max_length=3)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.reserva')),
            ],
        ),
    ]
